# Generated by Django 5.0.7 on 2024-08-01 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_project_team_id_alter_project_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_management',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.task'),
        ),
    ]
